#!/bin/bash
#this installs everything

sudo cp thinkdisp.py /usr/bin/thinkdisp.py
sudo cp killdisp1 /usr/bin/killdisp1
sudo cp killdisp2 /usr/bin/killdisp2
sudo cp start_thinkdisp /usr/bin/start_thinkdisp
mkdir -p ~/Documents/thinkdisp
sudo cp config.ini ~/Documents/thinkdisp/prefs.ini
mkdir -p ~/.config/autostart
sudo cp thinkdisp.desktop ~/.config/autostart/thinkdisp.desktop
sudo chmod +x /usr/bin/thinkdisp.py
sudo chmod +x /usr/bin/killdisp1
sudo chmod +x /usr/bin/killdisp2
sudo chmod +x /usr/bin/start_thinkdisp
