#!/bin/bash
#this installs everything

sudo cp thinkdisp.py /usr/bin/thinkdisp.py
sudo cp thinkdispk1 /usr/bin/thinkdispk1
sudo cp thinkdispk2 /usr/bin/thinkdispk2
sudo chmod +x /usr/bin/thinkdisp.py
sudo chmod +x /usr/bin/thinkdispk1
sudo chmod +x /usr/bin/thinkdispk2
