#!/bin/bash
#this installs everything

sudo cp thinkdisp.py /usr/bin/thinkdisp.py
sudo cp killdisp1 /usr/bin/killdisp1
sudo cp killdisp2 /usr/bin/killdisp2
mkdir -p ~/Documents/thinkdisp
sudo cp prefs.ini ~/Documents/thinkdisp/prefs.ini
sudo chmod +x /usr/bin/thinkdisp.py
sudo chmod +x /usr/bin/killdisp1
sudo chmod +x /usr/bin/killdisp2
