#!/bin/bash
# switches off the nvidia graphics card

echo "Removing nvidia module..."
sudo rmmod nvidia
sudo rmmod nouveau
sleep 1s



# echo Making first acpi call...
# echo "\_SB.PCI0.PEG.VID._DSM {0xF8,0xD8,0x86,0xA4,0xDA,0x0B,0x1B,0x47,0xA7,0x2B,0x60,0x42,0xA6,0xB5,0xBE,0xE0} 0x100 0x1A {0x1,0x0,0x0,0x3}" | sudo tee /proc/acpi/call
# sleep 1s
# 
# echo Making second acpi call...
# echo "\_SB.PCI0.PEG.VID._PS3" | sudo tee /proc/acpi/call
# sleep 1s
# 
# lspci -vnnn | grep VGA
echo "inserting bbswitch..."
sudo modprobe bbswitch
echo "bbswitching..."
sudo tee /proc/acpi/bbswitch <<<OFF
echo "New State:"
sudo cat /proc/acpi/bbswitch


